import yaml from "js-yaml";
import { join } from "path";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "fs";
import { HERMES_HOME } from "./installer";
import {
  initProfileRuntimeDb,
  insertProfile,
  insertRuntimeInstance,
  insertProfileEntry,
  insertCapability,
  insertSkill,
  insertAuditEvent,
  transaction,
  getProfileByName,
  checkPortConflict,
  generateId,
} from "./profile-runtime-db";
import type { ProfileErrorCode } from "../shared/profile-runtime/profile-runtime-contract";
import type { ImportRuntimeConfigResult } from "../shared/profile-runtime/profile-runtime-contract";

const VALID_NAME_REGEX = /^[a-z][a-z0-9-]{1,31}$/;

const VALID_RUNTIME_TYPES = new Set([
  "hermes-local",
  "hermes-remote",
  "tool-only",
  "docker-hermes",
  "browser-operator",
  "feishu-bridge",
]);

const VALID_CAPABILITIES = new Set([
  "delegation",
  "skill-sync",
  "session-share",
  "web-operator",
  "gateway-supervisor",
]);

interface ParsedProfileEntry {
  type: string;
  route: string;
  title: string;
  icon?: string;
}

interface ParsedProfile {
  displayName: string;
  role?: string;
  runtimeType: string;
  enabled?: boolean;
  autoStart?: boolean;
  port: number;
  model?: string;
  entry?: ParsedProfileEntry;
  capabilities?: string[];
  soulPrompt?: string;
}

interface ParsedConfig {
  version: number;
  runtime?: { db?: string; defaultAdapter?: string };
  gateway?: { host?: string; healthPath?: string };
  profiles: Record<string, ParsedProfile>;
}

function profileHome(name?: string): string {
  if (!name || name === "default") return HERMES_HOME;
  return join(HERMES_HOME, "profiles", name);
}

function makeError(profileName: string, errorCode: ProfileErrorCode, message: string) {
  return { profileName, errorCode, message };
}

function validateName(name: string): ProfileErrorCode | null {
  if (!VALID_NAME_REGEX.test(name)) return "PROFILE_INVALID_NAME";
  return null;
}

function validatePort(port: number): ProfileErrorCode | null {
  if (!Number.isInteger(port) || port < 1024 || port > 65535) return "PROFILE_CONFIG_INVALID";
  return null;
}

function validateRuntimeType(type: string): ProfileErrorCode | null {
  if (!VALID_RUNTIME_TYPES.has(type)) return "PROFILE_ADAPTER_NOT_FOUND";
  return null;
}

function validateCapabilities(caps?: string[]): ProfileErrorCode | null {
  if (!caps) return null;
  for (const cap of caps) {
    if (!VALID_CAPABILITIES.has(cap)) return "PROFILE_CAPABILITY_NOT_ENABLED";
  }
  return null;
}

function parseYaml(content: string): ParsedConfig {
  const raw = yaml.load(content) as Record<string, unknown>;
  if (!raw || typeof raw !== "object") throw new Error("Invalid YAML: expected object");
  if (raw.version !== 1) throw new Error(`Unsupported config version: ${raw.version}`);
  if (!raw.profiles || typeof raw.profiles !== "object") throw new Error("Missing 'profiles' section");
  return {
    version: raw.version as number,
    runtime: raw.runtime as ParsedConfig["runtime"],
    gateway: raw.gateway as ParsedConfig["gateway"],
    profiles: raw.profiles as Record<string, ParsedProfile>,
  };
}

function createProfileDirectories(name: string, soulPrompt?: string): string[] {
  const home = profileHome(name);
  const createdDirs: string[] = [];

  if (!existsSync(home)) {
    mkdirSync(home, { recursive: true });
    createdDirs.push(home);
  }

  const subdirs = ["skills", "memories", "desktop", "desktop/shared-context"];
  for (const sub of subdirs) {
    const dir = join(home, sub);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
      createdDirs.push(dir);
    }
  }

  if (name !== "default") {
    const envFile = join(home, ".env");
    if (!existsSync(envFile)) {
      writeFileSync(envFile, "# Auto-generated by Hermes Desktop profile-runtime\n", "utf-8");
    }
    const soulFile = join(home, "SOUL.md");
    if (!existsSync(soulFile)) {
      const content = soulPrompt || `# ${name} Agent\n\nYou are the ${name} specialist agent.\n`;
      writeFileSync(soulFile, content, "utf-8");
    }
  }

  return createdDirs;
}

export function importConfig(
  yamlContent: string,
  options?: { overwrite?: boolean },
): ImportRuntimeConfigResult {
  const overwrite = options?.overwrite ?? false;
  const errors: Array<{ profileName: string; errorCode: ProfileErrorCode; message: string }> = [];
  const importedNames: string[] = [];
  let allCreatedDirs: string[] = [];

  let config: ParsedConfig;
  try {
    config = parseYaml(yamlContent);
  } catch (e) {
    return {
      ok: false,
      importedCount: 0,
      errors: [{ profileName: "", errorCode: "PROFILE_CONFIG_INVALID", message: String(e) }],
    };
  }

  initProfileRuntimeDb();

  const profileEntries = Object.entries(config.profiles);

  const host = config.gateway?.host ?? "127.0.0.1";

  for (const [name, profileDef] of profileEntries) {
    const nameError = validateName(name);
    if (nameError) {
      errors.push(makeError(name, nameError, `Profile name "${name}" does not match ${VALID_NAME_REGEX.source}`));
      continue;
    }

    const portError = validatePort(profileDef.port);
    if (portError) {
      errors.push(makeError(name, "PROFILE_CONFIG_INVALID", `Invalid port: ${profileDef.port}`));
      continue;
    }

    const rtError = validateRuntimeType(profileDef.runtimeType);
    if (rtError) {
      errors.push(makeError(name, rtError, `Unknown runtime type: ${profileDef.runtimeType}`));
      continue;
    }

    const capError = validateCapabilities(profileDef.capabilities);
    if (capError) {
      errors.push(makeError(name, capError, "Invalid capability in list"));
      continue;
    }

    const existing = getProfileByName(name);
    if (existing && !overwrite) {
      errors.push(makeError(name, "PROFILE_ALREADY_EXISTS", `Profile "${name}" already exists`));
      continue;
    }

    const portConflict = checkPortConflict(host, profileDef.port, existing?.id);
    if (portConflict) {
      errors.push(makeError(name, "PROFILE_PORT_CONFLICT", `Port ${profileDef.port} already used by profile ${portConflict.profile_id}`));
      continue;
    }

    try {
      const createdDirs = createProfileDirectories(name, profileDef.soulPrompt);
      allCreatedDirs.push(...createdDirs);

      const isDefault = name === "default";
      const role = isDefault ? "aios-controller" as const : "specialist" as const;
      const profileId = existing?.id ?? generateId();
      const home = profileHome(name);
      const ts = new Date().toISOString();

      transaction(() => {
        if (existing) {
          const db = require("./profile-runtime-db").getDb();
          db.prepare("DELETE FROM profiles WHERE id = ?").run(existing.id);
        }

        insertProfile({
          id: profileId,
          name,
          display_name: profileDef.displayName,
          role,
          description: profileDef.role ?? null,
          runtime_type: profileDef.runtimeType as "hermes-local",
          profile_home: home,
          enabled: profileDef.enabled !== false,
          auto_start: profileDef.autoStart !== false,
          sort_order: isDefault ? 0 : Object.keys(config.profiles).indexOf(name),
        });

        insertRuntimeInstance({
          id: generateId(),
          profile_id: profileId,
          runtime_type: profileDef.runtimeType as "hermes-local",
          host,
          port: profileDef.port,
          base_url: `http://${host}:${profileDef.port}`,
          status: "not_deployed",
          pid: null,
          started_at: null,
          stopped_at: null,
          last_health_check_at: null,
          last_error: null,
          restart_count: 0,
          last_exit_code: null,
          last_crash_at: null,
          auto_restart: profileDef.autoStart !== false,
          health_fail_count: 0,
        });

        const entryDef = profileDef.entry;
        if (entryDef) {
          insertProfileEntry({
            id: generateId(),
            profile_id: profileId,
            entry_type: entryDef.type,
            route: entryDef.route,
            title: entryDef.title,
            icon: entryDef.icon ?? null,
            enabled: true,
            sort_order: isDefault ? 0 : Object.keys(config.profiles).indexOf(name),
            config_json: null,
          });
        } else {
          const defaultEntryType = isDefault ? "aios-workspace" : "specialist-workspace";
          const defaultRoute = isDefault ? "aios" : `profile/${name}`;
          const defaultIcon = isDefault ? "layout-dashboard" : "user";
          insertProfileEntry({
            id: generateId(),
            profile_id: profileId,
            entry_type: defaultEntryType,
            route: defaultRoute,
            title: profileDef.displayName,
            icon: defaultIcon,
            enabled: true,
            sort_order: isDefault ? 0 : Object.keys(config.profiles).indexOf(name),
            config_json: null,
          });
        }

        if (profileDef.capabilities) {
          for (const cap of profileDef.capabilities) {
            insertCapability({
              id: generateId(),
              profile_id: profileId,
              capability_name: cap as "delegation",
              enabled: true,
              config_json: null,
            });
          }
        }

        insertAuditEvent({
          id: generateId(),
          event_type: "profile_runtime",
          profile_id: profileId,
          source: "system",
          action: "import_profile",
          payload_json: JSON.stringify({ name, port: profileDef.port, runtimeType: profileDef.runtimeType }),
          status: "success",
          error_message: null,
        });
      });

      importedNames.push(name);
    } catch (e) {
      errors.push(makeError(name, "PROFILE_CONFIG_INVALID", `Import failed: ${String(e)}`));
    }
  }

  return {
    ok: errors.length === 0,
    importedCount: importedNames.length,
    errors,
  };
}

export function importConfigFromFile(
  filePath: string,
  options?: { overwrite?: boolean },
): ImportRuntimeConfigResult {
  if (!existsSync(filePath)) {
    return {
      ok: false,
      importedCount: 0,
      errors: [{ profileName: "", errorCode: "PROFILE_CONFIG_INVALID", message: `File not found: ${filePath}` }],
    };
  }
  const content = readFileSync(filePath, "utf-8");
  return importConfig(content, options);
}

export { profileHome };
